name: ci / test
on:
  push:
    branches:
      - ${{{ github.default_branch }}} 
  pull_request:
    branches:
      - ${{{ github.default_branch }}}
      
  jobs:

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: lts/*
    - run: ls -la
